// flow-typed signature: fdccf8737e1a981963556f8684b782bd
// flow-typed version: <<STUB>>/@smockle/matrix_v^3.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@smockle/matrix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@smockle/matrix' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@smockle/matrix/flow-typed/npm/@std/esm_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/codecov_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/colortape_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/eslint-config-standard_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/eslint-plugin-standard_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/jsdoc-to-markdown_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/mathjs_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/nyc_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/flow-typed/npm/prettier-eslint-cli_vx.x.x' {
  declare module.exports: any
}

declare module '@smockle/matrix/lib/matrix' {
  declare module.exports: any
}

// Filename aliases
declare module '@smockle/matrix/flow-typed/npm/@std/esm_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/@std/esm_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/codecov_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/codecov_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/colortape_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/colortape_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/eslint_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/eslint-config-standard_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/eslint-config-standard_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/eslint-plugin-import_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/eslint-plugin-node_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/eslint-plugin-promise_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/eslint-plugin-standard_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/eslint-plugin-standard_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/flow-bin_v0.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/flow-typed_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/husky_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/jsdoc-to-markdown_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/jsdoc-to-markdown_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/lint-staged_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/lodash_v4.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/mathjs_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/mathjs_vx.x.x'
  >
}
declare module '@smockle/matrix/flow-typed/npm/nyc_vx.x.x.js' {
  declare module.exports: $Exports<'@smockle/matrix/flow-typed/npm/nyc_vx.x.x'>
}
declare module '@smockle/matrix/flow-typed/npm/prettier-eslint-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    '@smockle/matrix/flow-typed/npm/prettier-eslint-cli_vx.x.x'
  >
}
declare module '@smockle/matrix/lib/matrix.js' {
  declare module.exports: $Exports<'@smockle/matrix/lib/matrix'>
}
